version: 2

project_name: CodexSessions

builds:
  - id: linux
    dir: ./specstory-cli
    main: ./main.go
    binary: csessions
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: targz
    ids:
      - linux
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - none*

checksum:
  name_template: checksums.txt

release:
  name_template: Codex Sessions {{.Tag}}

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
